name: umm_discovery_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - anndata=0.7.1=py37_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - faiss-gpu=1.6.3=py37h1a5d453_0
  - hdbscan=0.8.26=py37h03ebfcd_0
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - jupyter=1.0.0=py_2
  - matplotlib-base=3.2.1=py37h30547a4_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - numba=0.48.0=py37hb3f55d8_0
  - numpy=1.18.1=py37h8960a57_1
  - pandas=0.25.3=py37hb3f55d8_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=6.2.1=py37hd70f55b_1
  - pip=20.0.2=py_2
  - protobuf=3.8.0=py37he1b5a44_2
  - python=3.7.6=h357f687_2
  - pytorch=1.3.1=py3.7_cuda10.0.130_cudnn7.6.3_0
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scikit-learn=0.22.2.post1=py37hcdab131_0
  - scipy=1.4.1=py37h921218d_0
  - seaborn=0.9.0=py_2
  - tensorboard=1.15.0=py37_0
  - torchvision=0.4.2=cuda100py37hecfc37a_0
  - tqdm=4.46.1=pyh9f0ad1d_0
  - umap-learn=0.3.10=py37_1
  - pip:
    - multicoretsne==0.1
    - torchsummary==1.5.1

